const MEMBER_SHEET='LICENSE_MEMBERS',CATALOG_SHEET='PRODUCT_CATALOG';
const MEMBER_HEADERS=['USER_ID','EMAIL','NAME','PRODUCTS','ALLOWED_SUBJECTS','START_DATE','EXPIRES_AT','PAYMENT','STATUS','SYNC_STATUS','LAST_SYNC','NOTE'];
const CATALOG_HEADERS=['CODE','PRODUCT_CODE','TITLE','ACTIVE'];
function onOpen(){SpreadsheetApp.getUi().createMenu('License Members').addItem('Initial setup','setupLicenseMemberSheets').addSeparator().addItem('Import new members','importNewLicenseMembers').addItem('Refresh all members','refreshLicenseMembers').addSeparator().addItem('Push selected rows','pushSelectedLicenseRows').addItem('Push all rows','pushAllLicenseRows').addSeparator().addItem('Install sync trigger','installLicenseSyncTrigger').addItem('Remove sync trigger','removeLicenseSyncTrigger').addItem('Sync trigger status','licenseSyncTriggerStatus').addSeparator().addItem('PERMANENTLY delete selected members','deleteSelectedMembersPermanently').addToUi()}
function setupLicenseMemberSheets(){const ss=SpreadsheetApp.getActive(),m=getOrCreate_(ss,MEMBER_SHEET),c=getOrCreate_(ss,CATALOG_SHEET);setHeaders_(m,MEMBER_HEADERS);setHeaders_(c,CATALOG_HEADERS);if(c.getLastRow()<2)c.getRange(2,1,4,4).setValues([['REA','realestate','Real Estate',true],['INS','insurance','Insurance',true],['MOR','mortgage','Mortgage NMLS',true],['NOT','notary','Notary',true]]);const rule=SpreadsheetApp.newDataValidation().requireValueInList(['ACTIVE','INACTIVE','REFUNDED','EXPIRED','PENDING'],true).build();m.getRange(2,9,Math.max(1,m.getMaxRows()-1),1).setDataValidation(rule);m.setFrozenRows(1);c.setFrozenRows(1);m.autoResizeColumns(1,MEMBER_HEADERS.length);c.autoResizeColumns(1,CATALOG_HEADERS.length);SpreadsheetApp.getUi().alert('Setup complete. Add LICENSE_SYNC_URL and LICENSE_SYNC_SECRET in Script Properties.')}
function installLicenseSyncTrigger(){removeLicenseSyncTrigger();const minutes=Number(PropertiesService.getScriptProperties().getProperty('LICENSE_SYNC_TRIGGER_MINUTES')||60);ScriptApp.newTrigger('importNewLicenseMembers').timeBased().everyMinutes(Math.min(60,Math.max(5,minutes||60))).create();SpreadsheetApp.getUi().alert('Time-driven sync trigger installed.')}
function removeLicenseSyncTrigger(){ScriptApp.getProjectTriggers().forEach(t=>{if(t.getHandlerFunction()==='importNewLicenseMembers')ScriptApp.deleteTrigger(t)})}
function licenseSyncTriggerStatus(){const triggers=ScriptApp.getProjectTriggers().filter(t=>t.getHandlerFunction()==='importNewLicenseMembers');SpreadsheetApp.getUi().alert(triggers.length?`Sync trigger is installed (${triggers.length}).`:'No sync trigger installed. Use Install sync trigger from the menu.')}
function importNewLicenseMembers(){pullMembers_(false)}function refreshLicenseMembers(){pullMembers_(true)}
function pullMembers_(refreshAll){const data=callSync_({action:'pull'}),sheet=getOrCreate_(SpreadsheetApp.getActive(),MEMBER_SHEET);setHeaders_(sheet,MEMBER_HEADERS);syncCatalog_(data.products||[]);const rows=sheetRows_(sheet),byId=new Map(rows.map((r,i)=>[String(r[0]),i+2]));let added=0,updated=0;(data.members||[]).forEach(m=>{const codes=(m.products||[]).map(productCodeToShort_).filter(Boolean).join(','),subjects=(m.entitlements||[]).filter(e=>e.status==='active'&&Array.isArray(e.allowed_subjects)&&e.allowed_subjects.length).map(e=>`${productCodeToShort_(e.product_code)||e.product_code}:${e.allowed_subjects.join('|')}`).join('; '),existing=byId.get(m.user_id);if(existing&&!refreshAll)return;const values=[m.user_id,m.email,m.name,codes,subjects,'','',codes?'PAID':'UNPAID',m.member_active===false?'INACTIVE':'ACTIVE',existing?'REFRESHED':'NEW',new Date(),''];if(existing){sheet.getRange(existing,1,1,MEMBER_HEADERS.length).setValues([values]);updated++}else{sheet.appendRow(values);added++}});SpreadsheetApp.getUi().alert(`Import complete: ${added} new, ${updated} refreshed.`)}
function pushSelectedLicenseRows(){const s=SpreadsheetApp.getActiveSheet();if(s.getName()!==MEMBER_SHEET)throw Error(`Run this from ${MEMBER_SHEET}.`);const r=s.getActiveRange(),start=Math.max(2,r.getRow()),count=r.getNumRows()-(start-r.getRow());pushRows_(s,start,Math.max(1,count))}
function pushAllLicenseRows(){const s=getOrCreate_(SpreadsheetApp.getActive(),MEMBER_SHEET);if(s.getLastRow()>=2)pushRows_(s,2,s.getLastRow()-1)}
function selectedMemberRows_(){const s=SpreadsheetApp.getActiveSheet();if(s.getName()!==MEMBER_SHEET)throw Error(`Run this from ${MEMBER_SHEET}.`);const r=s.getActiveRange(),start=Math.max(2,r.getRow()),count=r.getNumRows()-(start-r.getRow());if(count<1)throw Error('Select one or more member rows.');return{sheet:s,start,count,values:s.getRange(start,1,count,MEMBER_HEADERS.length).getValues()}}
function deleteSelectedMembersPermanently(){const x=selectedMemberRows_(),ids=x.values.map(r=>String(r[0]||'').trim()).filter(Boolean),ui=SpreadsheetApp.getUi();if(ids.length!==x.count)throw Error('Every selected row must have USER_ID.');if(ui.alert('Delete selected members?',`Delete ${ids.length} selected member account(s) and their License access?`,ui.ButtonSet.YES_NO)!==ui.Button.YES)return;const result=callSync_({action:'delete_members',user_ids:ids}),failed=(result.results||[]).filter(r=>!r.ok);if(failed.length){failed.forEach(f=>{const i=ids.indexOf(f.user_id);if(i>=0)x.sheet.getRange(x.start+i,10).setValue('DELETE ERROR: '+f.error)});ui.alert(`Deleted ${(result.results||[]).length-failed.length}; failed ${failed.length}.`);return}x.sheet.deleteRows(x.start,x.count);ui.alert(`${ids.length} member account(s) were deleted.`)}
function pushRows_(sheet,start,count){const values=sheet.getRange(start,1,count,MEMBER_HEADERS.length).getValues(),map=catalogMap_(),payload=[],source=[];values.forEach((r,i)=>{if(!r[0]&&!r[1])return;const products=String(r[3]||'').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean).map(x=>x==='ALL'?'ALL':map[x]).filter(Boolean),subjects=parseAllowedSubjects_(r[4],map);payload.push({user_id:r[0],email:r[1],products,subjects,starts_at:dateIso_(r[5]),expires_at:dateIso_(r[6]),payment:r[7],status:String(r[8]||'ACTIVE').toLowerCase(),note:r[11]});source.push(start+i)});const result=callSync_({action:'push',rows:payload});(result.results||[]).forEach((r,i)=>{sheet.getRange(source[i],10).setValue(r.ok?'OK':'ERROR: '+r.error);sheet.getRange(source[i],11).setValue(new Date())});SpreadsheetApp.getUi().alert(`Sync complete: ${(result.results||[]).filter(r=>r.ok).length}/${payload.length}`)}
function callSync_(body){const p=PropertiesService.getScriptProperties(),url=p.getProperty('LICENSE_SYNC_URL'),secret=p.getProperty('LICENSE_SYNC_SECRET');if(!url||!secret)throw Error('LICENSE_SYNC_URL and LICENSE_SYNC_SECRET are required in Script Properties.');const res=UrlFetchApp.fetch(url,{method:'post',contentType:'application/json',headers:{'x-license-sync-secret':secret},payload:JSON.stringify(body),muteHttpExceptions:true}),text=res.getContentText(),data=JSON.parse(text||'{}');if(res.getResponseCode()>=300)throw Error(data.error||text);return data}
function syncCatalog_(products){const s=getOrCreate_(SpreadsheetApp.getActive(),CATALOG_SHEET);setHeaders_(s,CATALOG_HEADERS);const existing=catalogMap_(),reverse={realestate:'REA',insurance:'INS',mortgage:'MOR',notary:'NOT'};products.forEach(p=>{if(!Object.values(existing).includes(p.product_code))s.appendRow([reverse[p.product_code]||p.product_code.slice(0,3).toUpperCase(),p.product_code,p.title,p.active!==false])})}
function catalogMap_(){const s=getOrCreate_(SpreadsheetApp.getActive(),CATALOG_SHEET),rows=s.getLastRow()<2?[]:s.getRange(2,1,s.getLastRow()-1,4).getValues(),map={};rows.forEach(r=>{if(r[0]&&r[1]&&r[3]!==false)map[String(r[0]).trim().toUpperCase()]=String(r[1]).trim()});return map}
function productCodeToShort_(code){const map=catalogMap_();return Object.keys(map).find(k=>map[k]===code)||String(code).slice(0,3).toUpperCase()}
function sheetRows_(s){return s.getLastRow()<2?[]:s.getRange(2,1,s.getLastRow()-1,MEMBER_HEADERS.length).getValues()}
function getOrCreate_(ss,name){return ss.getSheetByName(name)||ss.insertSheet(name)}function setHeaders_(s,h){s.getRange(1,1,1,h.length).setValues([h]).setFontWeight('bold').setBackground('#075ea8').setFontColor('#fff')}
function dateIso_(v){return v instanceof Date?v.toISOString():(String(v||'').trim()||null)}
// ALLOWED_SUBJECTS cell format: "REA:Real Estate Law|Real Estate Finance; INS:General Insurance".
// Products omitted from the cell keep full product access; "REA:" alone is ignored.
function parseAllowedSubjects_(cell,map){const out={},text=String(cell||'').trim();if(!text)return out;text.split(';').forEach(part=>{const m=part.match(/^\s*([A-Za-z]{2,12})\s*:\s*(.+)$/);if(!m)return;const code=map[m[1].trim().toUpperCase()];if(!code)return;const list=m[2].split('|').map(s=>s.trim()).filter(s=>s&&s.length<=120);if(list.length)out[code]=[...new Set(list)]});return out}
